-- CRIANDO A DATABASE
CREATE DATABASE aula28_08
USE aula28_08


-- CRIANDO AS TABELAS
CREATE TABLE FUNCIONARIO (
    cpf varchar(11) NOT NULL,
	nome varchar(200) NOT NULL,
	salario decimal(5,2) NOT NULL
)

CREATE TABLE AUDITORIA_FUNCIONARIO (
    data_hora DATETIME NOT NULL,
	nome varchar(200) NOT NULL,
	salario_antigo decimal(5,2) NOT NULL,
	salario_novo decimal(5,2) NOT NULL

)


--ALIMENTANDO AS TABELAS
INSERT INTO FUNCIONARIO(cpf, nome, salario) VALUES ('11122233301', 'Paulo Moita', 100.45);
INSERT INTO FUNCIONARIO(cpf, nome, salario) VALUES ('11122233302', 'Ana Banana', 80.00);
INSERT INTO FUNCIONARIO(cpf, nome, salario) VALUES ('11122233303', 'Beto Bolado', 67.00);
INSERT INTO FUNCIONARIO(cpf, nome, salario) VALUES ('11122233304', 'Chico', 98.50);


-- TRIGGER PARA ALIMENTAR A SEGUNDA TABELA
CREATE TRIGGER atualizandoFuncionario 
ON FUNCIONARIO
FOR UPDATE
AS
BEGIN
	IF (SELECT COUNT(*) FROM INSERTED) = 1 AND (SELECT COUNT(*) FROM DELETED) = 1
		INSERT INTO AUDITORIA_FUNCIONARIO(data_hora, nome, salario_antigo, salario_novo)
		VALUES (GETDATE(), (SELECT nome FROM inserted), (SELECT salario FROM deleted), (SELECT salario FROM inserted));
END


-- TESTANDO A TRIGGER
UPDATE FUNCIONARIO SET salario = 450 WHERE cpf = '11122233301'
UPDATE FUNCIONARIO SET salario = 300 WHERE cpf = '11122233303'


-- CRIANDO PROCEDURE PARA A QUESTÃO 2
ALTER PROCEDURE verLog
AS
BEGIN
	SELECT
		cpf 'CPF',
		nome 'Nome',
		(SELECT COUNT(*) FROM AUDITORIA_FUNCIONARIO WHERE AUDITORIA_FUNCIONARIO.nome = FUNCIONARIO.nome) 'Qtd. de Modificações'
	FROM
		FUNCIONARIO
END

-- QUESTÃO 2
EXECUTE verLog